import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../theme/app_theme.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';
import '../services/attendance_services.dart';
import '../services/break_time_services.dart';
import '../models/break_time.dart';
import '../widgets/loader.dart';
import 'attendance_ist_time.dart';

class DownloadSheet extends StatefulWidget {
  final List<Map<String, dynamic>> employees;
  final int adminId;
  const DownloadSheet({
    required this.employees,
    required this.adminId,
    super.key,
  });

  @override
  State<DownloadSheet> createState() => _DownloadSheetState();
}

class _DownloadSheetState extends State<DownloadSheet> {
  final AttendanceService _attendanceService = AttendanceService();
  final BreakTimeService _breakTimeService = BreakTimeService();
  bool _isLoading = false;
  int? selectedEmployeeId;
  int selectedMonth = DateTime.now().month;
  int selectedYear = DateTime.now().year;

  String _formatWorkDuration(Duration duration) {
    final totalMinutes = duration.inMinutes;
    final hours = totalMinutes ~/ 60;
    final minutes = totalMinutes % 60;
    return '${hours} hr ${minutes} mins';
  }

  PdfColor _pdfColorFromHex(int rgb) {
    final r = ((rgb >> 16) & 0xFF) / 255.0;
    final g = ((rgb >> 8) & 0xFF) / 255.0;
    final b = (rgb & 0xFF) / 255.0;
    return PdfColor(r, g, b);
  }

  Future<void> _downloadPdf() async {
    if (selectedEmployeeId == null) return;
    setState(() => _isLoading = true);
    try {
      pw.ImageProvider? logoProvider;
      try {
        final bytes = await rootBundle.load('assets/logo/attendx24_logo.png');
        logoProvider = pw.MemoryImage(bytes.buffer.asUint8List());
      } catch (_) {
        logoProvider = null;
      }

      final selectedEmployee = widget.employees.firstWhere(
        (e) => e['id'] == selectedEmployeeId,
        orElse: () => <String, dynamic>{},
      );
      final employeeName = (selectedEmployee['name'] ?? '').toString();

      final pdfBrown = _pdfColorFromHex(0x554E3E);
      final pdfGreen = _pdfColorFromHex(0x12A30D);
      final pdfMuted = _pdfColorFromHex(0x818080);
      final pdfBg = _pdfColorFromHex(0xF5F5F7);

      // Fetch attendance data
      final attendanceList = await _attendanceService
          .fetchAttendanceByAdminAndEmployee(
            widget.adminId,
            selectedEmployeeId!,
          );
      // Filter by selected month/year
      final filteredAttendance = attendanceList.where((a) {
        final dateIst =
            tryParseApiDateTimeAsIst(a.date) ??
            tryParseApiDateTimeAsIst(a.checkInTime) ??
            DateTime.tryParse(a.date);
        return dateIst != null &&
            dateIst.month == selectedMonth &&
            dateIst.year == selectedYear;
      }).toList();

      // Fetch all breaks for this employee
      final breakList = await _breakTimeService.fetchBreaksByAdminAndEmployee(
        widget.adminId,
        selectedEmployeeId!,
      );

      // Group breaks by attendanceId for quick lookup
      final breaksByAttendance = <int, List<BreakTime>>{};
      for (final b in breakList) {
        breaksByAttendance.putIfAbsent(b.attendanceId, () => []).add(b);
      }

      // Generate PDF
      final pdf = pw.Document();
      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            pageFormat: PdfPageFormat.a4,
            margin: const pw.EdgeInsets.fromLTRB(28, 28, 28, 26),
            buildBackground: (context) {
              if (logoProvider == null) return pw.SizedBox();
              return pw.FullPage(
                ignoreMargins: true,
                child: pw.Stack(
                  children: [
                    pw.Container(color: PdfColors.white),
                    pw.Center(
                      child: pw.Opacity(
                        opacity: 0.06,
                        child: pw.Transform.rotate(
                          angle: -0.35,
                          child: pw.Image(logoProvider, width: 320),
                        ),
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
          footer: (context) {
            return pw.Padding(
              padding: const pw.EdgeInsets.only(top: 10),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'Generated by AttendX24',
                    style: pw.TextStyle(fontSize: 9, color: pdfMuted),
                  ),
                  pw.Text(
                    'Page ${context.pageNumber} of ${context.pagesCount}',
                    style: pw.TextStyle(fontSize: 9, color: pdfMuted),
                  ),
                ],
              ),
            );
          },
          build: (context) {
            return [
              pw.Container(
                padding: const pw.EdgeInsets.all(14),
                decoration: pw.BoxDecoration(
                  color: pdfBg,
                  borderRadius: pw.BorderRadius.circular(12),
                  border: pw.Border.all(color: PdfColors.grey300, width: 0.8),
                ),
                child: pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.center,
                  children: [
                    if (logoProvider != null)
                      pw.Container(
                        width: 44,
                        height: 44,
                        padding: const pw.EdgeInsets.all(6),
                        decoration: pw.BoxDecoration(
                          color: PdfColors.white,
                          borderRadius: pw.BorderRadius.circular(12),
                          border: pw.Border.all(
                            color: PdfColors.grey300,
                            width: 0.8,
                          ),
                        ),
                        child: pw.Image(logoProvider),
                      )
                    else
                      pw.Container(
                        width: 44,
                        height: 44,
                        decoration: pw.BoxDecoration(
                          color: PdfColors.white,
                          borderRadius: pw.BorderRadius.circular(12),
                          border: pw.Border.all(
                            color: PdfColors.grey300,
                            width: 0.8,
                          ),
                        ),
                      ),
                    pw.SizedBox(width: 12),
                    pw.Expanded(
                      child: pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(
                            'Attendance Sheet',
                            style: pw.TextStyle(
                              fontSize: 20,
                              fontWeight: pw.FontWeight.bold,
                              color: pdfBrown,
                            ),
                          ),
                          pw.SizedBox(height: 3),
                          pw.Text(
                            'Employee: $employeeName',
                            style: pw.TextStyle(fontSize: 11, color: pdfMuted),
                          ),
                          pw.Text(
                            'Month: ${selectedMonth.toString().padLeft(2, '0')} / $selectedYear',
                            style: pw.TextStyle(fontSize: 11, color: pdfMuted),
                          ),
                        ],
                      ),
                    ),
                    pw.Container(
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal: 10,
                        vertical: 6,
                      ),
                      decoration: pw.BoxDecoration(
                        color: pdfGreen,
                        borderRadius: pw.BorderRadius.circular(18),
                      ),
                      child: pw.Text(
                        'IST',
                        style: pw.TextStyle(
                          fontSize: 10,
                          color: PdfColors.white,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 14),
              pw.TableHelper.fromTextArray(
                headers: [
                  'Date',
                  'Check In',
                  'Check Out',
                  'Break In',
                  'Break Out',
                  'Total Work',
                ],
                data: filteredAttendance.map((a) {
                  final breaks = breaksByAttendance[a.attendanceId] ?? [];
                  final breakIn = breaks.isNotEmpty
                      ? formatIstTime(
                          breaks.first.breakInTime,
                          use24Hour: true,
                          showSeconds: true,
                        )
                      : '-';
                  final breakOut = breaks.isNotEmpty
                      ? formatIstTime(
                          breaks.last.breakOutTime,
                          use24Hour: true,
                          showSeconds: true,
                        )
                      : '-';
                  final checkIn = formatIstTime(
                    a.checkInTime,
                    use24Hour: true,
                    showSeconds: true,
                  );
                  final checkOut = formatIstTime(
                    a.checkOutTime,
                    use24Hour: true,
                    showSeconds: true,
                  );
                  // Calculate total work duration (excluding breaks)
                  var workDuration = Duration.zero;
                  final inTimeUtc = tryParseApiDateTimeAsUtc(a.checkInTime);
                  final outTimeUtc = tryParseApiDateTimeAsUtc(a.checkOutTime);
                  if (inTimeUtc != null &&
                      outTimeUtc != null &&
                      outTimeUtc.isAfter(inTimeUtc)) {
                    workDuration = outTimeUtc.difference(inTimeUtc);
                    // Subtract break durations
                    for (final br in breaks) {
                      if (br.breakInTime != null && br.breakOutTime != null) {
                        final binUtc = tryParseApiDateTimeAsUtc(br.breakInTime);
                        final boutUtc = tryParseApiDateTimeAsUtc(
                          br.breakOutTime,
                        );
                        if (binUtc != null &&
                            boutUtc != null &&
                            boutUtc.isAfter(binUtc)) {
                          workDuration -= boutUtc.difference(binUtc);
                        }
                      }
                    }
                    if (workDuration.isNegative) workDuration = Duration.zero;
                  }
                  return [
                    formatIstDateYmd(a.date),
                    checkIn,
                    checkOut,
                    breakIn,
                    breakOut,
                    _formatWorkDuration(workDuration),
                  ];
                }).toList(),
                cellStyle: pw.TextStyle(fontSize: 9.6, color: pdfBrown),
                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 10.5,
                  color: PdfColors.white,
                ),
                cellAlignment: pw.Alignment.center,
                headerDecoration: pw.BoxDecoration(color: pdfBrown),
                border: pw.TableBorder.all(
                  color: PdfColors.grey300,
                  width: 0.6,
                ),
              ),
            ];
          },
        ),
      );

      await Printing.layoutPdf(onLayout: (format) async => pdf.save());
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to generate PDF: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(26),
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
        child: Container(
          decoration: BoxDecoration(
            color: kWhite.withAlpha(230),
            borderRadius: BorderRadius.circular(26),
            border: Border.all(
              color: kBlack.withAlpha((0.06 * 255).toInt()),
              width: 1.2,
            ),
            boxShadow: [
              BoxShadow(
                color: kBlack.withAlpha((0.10 * 255).toInt()),
                blurRadius: 26,
                offset: const Offset(0, 14),
              ),
            ],
          ),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 26),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      color: kWhiteGrey.withAlpha(170),
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                        color: kBlack.withAlpha((0.06 * 255).toInt()),
                      ),
                    ),
                    child: Icon(Icons.picture_as_pdf, color: kGreen, size: 22),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Download Attendance Sheet',
                      style: kHeaderTextStyle(context).copyWith(fontSize: 18),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 18),
              Text('Employee', style: kCaptionTextStyle(context)),
              const SizedBox(height: 6),
              DropdownButtonFormField<int>(
                initialValue: selectedEmployeeId,
                isExpanded: true,
                hint: Text(
                  'Select employee',
                  style: kCaptionTextStyle(context).copyWith(
                    color: kBrown.withAlpha((0.72 * 255).toInt()),
                    fontWeight: FontWeight.w800,
                  ),
                ),
                items: widget.employees
                    .map(
                      (e) => DropdownMenuItem<int>(
                        value: e['id'] as int?,
                        child: Text(
                          (e['name'] ?? '').toString(),
                          overflow: TextOverflow.ellipsis,
                          style: kCaptionTextStyle(context).copyWith(
                            fontWeight: FontWeight.w900,
                            color: kBrown,
                          ),
                        ),
                      ),
                    )
                    .toList(),
                onChanged: (val) => setState(() => selectedEmployeeId = val),
                decoration: InputDecoration(
                  filled: true,
                  fillColor: kWhiteGrey.withAlpha(170),
                  prefixIcon: Icon(
                    Icons.badge_outlined,
                    color: kBrown.withAlpha((0.82 * 255).toInt()),
                  ),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(18),
                    borderSide: BorderSide.none,
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 10,
                  ),
                ),
              ),
              const SizedBox(height: 14),
              Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Month', style: kCaptionTextStyle(context)),
                        const SizedBox(height: 6),
                        DropdownButtonFormField<int>(
                          initialValue: selectedMonth,
                          items: List.generate(
                            12,
                            (i) => DropdownMenuItem(
                              value: i + 1,
                              child: Text('${i + 1}'.padLeft(2, '0')),
                            ),
                          ),
                          onChanged: (val) => setState(
                            () => selectedMonth = val ?? selectedMonth,
                          ),
                          decoration: InputDecoration(
                            filled: true,
                            fillColor: kWhiteGrey.withAlpha(170),
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(18),
                              borderSide: BorderSide.none,
                            ),
                            contentPadding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 10,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Year', style: kCaptionTextStyle(context)),
                        const SizedBox(height: 6),
                        DropdownButtonFormField<int>(
                          initialValue: selectedYear,
                          items: List.generate(6, (i) {
                            final year = DateTime.now().year - 3 + i;
                            return DropdownMenuItem(
                              value: year,
                              child: Text('$year'),
                            );
                          }),
                          onChanged: (val) => setState(
                            () => selectedYear = val ?? selectedYear,
                          ),
                          decoration: InputDecoration(
                            filled: true,
                            fillColor: kWhiteGrey.withAlpha(170),
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(18),
                              borderSide: BorderSide.none,
                            ),
                            contentPadding: const EdgeInsets.symmetric(
                              horizontal: 12,
                              vertical: 10,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),
              Center(
                child: _isLoading
                    ? const AttendX24Loader(
                        text: 'Generating PDF…',
                        logoSize: 60,
                      )
                    : SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          icon: const Icon(Icons.download),
                          label: const Text('Download PDF'),
                          style: kPremiumButtonStyle(context),
                          onPressed: selectedEmployeeId == null
                              ? null
                              : _downloadPdf,
                        ),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
