
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/employee.dart';

class EmployeeDownloadPdf {
	static const String _watermarkAssetPath =
			'assets/logo/attendx24_logo.png';

	static Future<void> downloadEmployeeRecords({
		required BuildContext context,
		required List<Employee> employees,
	}) async {
		if (employees.isEmpty) return;

		await Printing.layoutPdf(
			onLayout: (format) async {
				return _buildEmployeeRecordsPdf(employees);
			},
			name: 'AttendX24_Employee_Records.pdf',
		);
	}

	static Future<Uint8List> _buildEmployeeRecordsPdf(
		List<Employee> employees,
	) async {
		final doc = pw.Document();
		final watermark = await _loadWatermarkImage();
		final now = DateTime.now();

		doc.addPage(
			pw.MultiPage(
				pageTheme: pw.PageTheme(
					pageFormat: PdfPageFormat.a4.landscape,
					margin: const pw.EdgeInsets.fromLTRB(28, 24, 28, 28),
					buildBackground: (_) {
						return pw.FullPage(
							ignoreMargins: true,
							child: pw.Opacity(
								opacity: 0.07,
								child: pw.Center(
									child: pw.Transform.rotate(
										angle: -0.35,
										child: pw.Column(
											mainAxisSize: pw.MainAxisSize.min,
											children: [
												if (watermark != null)
													pw.Image(watermark, width: 320)
												else
													pw.SizedBox(height: 220),
												pw.SizedBox(height: 10),
												pw.Text(
													'AttendX24',
													style: pw.TextStyle(
														fontSize: 54,
														fontWeight: pw.FontWeight.bold,
														color: PdfColors.grey700,
													),
												),
											],
										),
									),
								),
							),
						);
					},
				),
				footer: (context) {
					return pw.Padding(
						padding: const pw.EdgeInsets.only(top: 10),
						child: pw.Row(
							mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
							children: [
								pw.Text(
									'Generated by AttendX24',
									style:
											const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
								),
								pw.Text(
									'Page ${context.pageNumber} of ${context.pagesCount}',
									style:
											const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
								),
							],
						),
					);
				},
				build: (_) {
					final headers = <String>[
						'ID',
						'Name',
						'Phone',
						'Email',
						'Password',
						'Bank',
						'Branch',
						'Account No',
						'IFSC',
						'Designation',
						'Address',
					];

					final data = employees
							.map(
								(e) => <String>[
									(e.employeeId ?? '').toString(),
									e.name,
									e.phone,
									e.email,
									e.password,
									e.bankName,
									e.branchName,
									e.accountNo,
									e.ifsc,
									e.designation,
									e.address,
								],
							)
							.toList();

					return [
						pw.Row(
							crossAxisAlignment: pw.CrossAxisAlignment.end,
							mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
							children: [
								pw.Column(
									crossAxisAlignment: pw.CrossAxisAlignment.start,
									children: [
										pw.Text(
											'Employee Records',
											style: pw.TextStyle(
												fontSize: 20,
												fontWeight: pw.FontWeight.bold,
											),
										),
										pw.SizedBox(height: 2),
										pw.Text(
											'Total: ${employees.length}',
											style: const pw.TextStyle(
												fontSize: 10,
												color: PdfColors.grey800,
											),
										),
									],
								),
								pw.Text(
									'${now.day.toString().padLeft(2, '0')}/${now.month.toString().padLeft(2, '0')}/${now.year}',
									style:
											const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
								),
							],
						),
						pw.SizedBox(height: 14),
						pw.TableHelper.fromTextArray(
							headers: headers,
							data: data,
							headerStyle: pw.TextStyle(
								fontSize: 9,
								fontWeight: pw.FontWeight.bold,
								color: PdfColors.white,
							),
							headerDecoration: const pw.BoxDecoration(color: PdfColors.black),
							cellStyle: const pw.TextStyle(fontSize: 8, color: PdfColors.black),
							cellAlignment: pw.Alignment.centerLeft,
							cellPadding:
									const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
							rowDecoration: pw.BoxDecoration(
								border: pw.Border(
									bottom:
											pw.BorderSide(color: PdfColors.grey300, width: 0.6),
								),
							),
							columnWidths: <int, pw.TableColumnWidth>{
								0: const pw.FixedColumnWidth(30),
								1: const pw.FixedColumnWidth(90),
								2: const pw.FixedColumnWidth(70),
								3: const pw.FixedColumnWidth(110),
								4: const pw.FixedColumnWidth(70),
								5: const pw.FixedColumnWidth(70),
								6: const pw.FixedColumnWidth(70),
								7: const pw.FixedColumnWidth(80),
								8: const pw.FixedColumnWidth(55),
								9: const pw.FixedColumnWidth(85),
								10: const pw.FlexColumnWidth(),
								11: const pw.FixedColumnWidth(100),
							},
						),
					];
				},
			),
		);

		return doc.save();
	}

	static Future<pw.ImageProvider?> _loadWatermarkImage() async {
		try {
			final bytes = await rootBundle.load(_watermarkAssetPath);
			return pw.MemoryImage(bytes.buffer.asUint8List());
		} catch (_) {
			return null;
		}
	}
}
