import 'package:flutter/services.dart' show rootBundle;

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/holiday.dart';
import '../theme/app_theme.dart';

PdfColor _pdfColorFromRgbInt(int rgb) {
  final r = ((rgb >> 16) & 0xFF) / 255.0;
  final g = ((rgb >> 8) & 0xFF) / 255.0;
  final b = (rgb & 0xFF) / 255.0;
  return PdfColor(r, g, b);
}

String _formatYmd(DateTime date) {
  final dd = date.day.toString().padLeft(2, '0');
  final mm = date.month.toString().padLeft(2, '0');
  final yyyy = date.year.toString();
  return '$dd/$mm/$yyyy';
}

/// Opens a print-preview dialog and allows downloading/printing the entire holiday list.
Future<void> openHolidayListPdfPrintPreview({
  required List<Holiday> holidays,
}) async {
  final sorted = holidays.toList()..sort((a, b) => a.date.compareTo(b.date));

  pw.ImageProvider? logoProvider;
  try {
    final bytes = await rootBundle.load('assets/logo/attendx24_logo.png');
    logoProvider = pw.MemoryImage(bytes.buffer.asUint8List());
  } catch (_) {
    logoProvider = null;
  }

  final pdfBrown = _pdfColorFromRgbInt(kBrown.value & 0xFFFFFF);
  final pdfGreen = _pdfColorFromRgbInt(kGreen.value & 0xFFFFFF);
  final pdfMuted = _pdfColorFromRgbInt(0x818080);
  final pdfBg = _pdfColorFromRgbInt(0xF5F5F7);

  final doc = pw.Document();
  doc.addPage(
    pw.MultiPage(
      pageTheme: pw.PageTheme(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(28, 28, 28, 26),
        buildBackground: (context) {
          if (logoProvider == null) return pw.SizedBox();
          return pw.FullPage(
            ignoreMargins: true,
            child: pw.Stack(
              children: [
                pw.Container(color: PdfColors.white),
                pw.Center(
                  child: pw.Opacity(
                    opacity: 0.06,
                    child: pw.Transform.rotate(
                      angle: -0.35,
                      child: pw.Image(logoProvider, width: 320),
                    ),
                  ),
                ),
              ],
            ),
          );
        },
      ),
      footer: (context) {
        return pw.Padding(
          padding: const pw.EdgeInsets.only(top: 10),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by AttendX24',
                style: pw.TextStyle(fontSize: 9, color: pdfMuted),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(fontSize: 9, color: pdfMuted),
              ),
            ],
          ),
        );
      },
      build: (context) {
        return [
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: pdfBg,
              borderRadius: pw.BorderRadius.circular(12),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.8),
            ),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                if (logoProvider != null)
                  pw.Container(
                    width: 44,
                    height: 44,
                    padding: const pw.EdgeInsets.all(6),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.white,
                      borderRadius: pw.BorderRadius.circular(12),
                      border: pw.Border.all(
                        color: PdfColors.grey300,
                        width: 0.8,
                      ),
                    ),
                    child: pw.Image(logoProvider),
                  )
                else
                  pw.Container(
                    width: 44,
                    height: 44,
                    decoration: pw.BoxDecoration(
                      color: PdfColors.white,
                      borderRadius: pw.BorderRadius.circular(12),
                      border: pw.Border.all(
                        color: PdfColors.grey300,
                        width: 0.8,
                      ),
                    ),
                  ),
                pw.SizedBox(width: 12),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Holiday List',
                        style: pw.TextStyle(
                          fontSize: 20,
                          fontWeight: pw.FontWeight.bold,
                          color: pdfBrown,
                        ),
                      ),
                      pw.SizedBox(height: 3),
                      pw.Text(
                        'Total holidays: ${sorted.length}',
                        style: pw.TextStyle(fontSize: 11, color: pdfMuted),
                      ),
                      pw.Text(
                        'Generated: ${_formatYmd(DateTime.now())}',
                        style: pw.TextStyle(fontSize: 11, color: pdfMuted),
                      ),
                    ],
                  ),
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                    horizontal: 10,
                    vertical: 6,
                  ),
                  decoration: pw.BoxDecoration(
                    color: pdfGreen,
                    borderRadius: pw.BorderRadius.circular(18),
                  ),
                  child: pw.Text(
                    'AttendX24',
                    style: pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.white,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 14),
          pw.TableHelper.fromTextArray(
            headers: const ['Date', 'Title', 'Remarks'],
            data: sorted
                .map(
                  (h) => [
                    _formatYmd(h.date),
                    h.occasion,
                    h.remarks.trim().isEmpty ? '-' : h.remarks,
                  ],
                )
                .toList(),
            headerDecoration: pw.BoxDecoration(
              color: pdfBrown,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            headerStyle: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            cellStyle: pw.TextStyle(fontSize: 10, color: PdfColors.black),
            cellAlignment: pw.Alignment.centerLeft,
            headerAlignment: pw.Alignment.centerLeft,
            cellPadding: const pw.EdgeInsets.symmetric(
              horizontal: 8,
              vertical: 8,
            ),
            columnWidths: {
              0: const pw.FixedColumnWidth(90),
              1: const pw.FlexColumnWidth(2.2),
              2: const pw.FlexColumnWidth(3),
            },
            border: pw.TableBorder(
              horizontalInside: pw.BorderSide(
                color: PdfColors.grey300,
                width: 0.8,
              ),
              verticalInside: pw.BorderSide(
                color: PdfColors.grey300,
                width: 0.8,
              ),
              left: pw.BorderSide(color: PdfColors.grey300, width: 0.8),
              right: pw.BorderSide(color: PdfColors.grey300, width: 0.8),
              top: pw.BorderSide(color: PdfColors.grey300, width: 0.8),
              bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.8),
            ),
          ),
        ];
      },
    ),
  );

  await Printing.layoutPdf(onLayout: (_) async => doc.save());
}
